version: 2
jobs:

    test_optimus:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh optimus
                  no_output_timeout: 1.5h


    test_optimus_snrna:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh optimus_snrna
                  no_output_timeout: 1.5h

    test_optimus_v3:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh optimus prV3
                  no_output_timeout: 1.5h

    test_smartseq2:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh smartseq2_single_sample
                  no_output_timeout: 1.5h

    test_smartseq2_multisample:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh smartseq2_multisample
                  no_output_timeout: 1.5h

    test_smartseq2_multisample_single_end:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh smartseq2_multisample pr_single_end
                  no_output_timeout: 1.5h

    test_smartseq2_single_end:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh smartseq2_single_sample pr_single_end
                  no_output_timeout: 1.5h

    test_optimus_mouse:
        machine:
            image: ubuntu-2004:202201-02

        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh optimus_mouse
                  no_output_timeout: 1.5h

    test_emptyDropsWrapper:
        docker:
            - image: quay.io/humancellatlas/secondary-analysis-dropletutils:0.1.0
        steps:
            - checkout
            - run:
                  command: |
                      cd docker/emptydrops/emptyDropsWrapper/test/
                      ./test_emptyDropsWrapper.sh

    test_npz2rds:
        docker:
            - image: quay.io/humancellatlas/secondary-analysis-dropletutils:0.1.2
        steps:
            - checkout
            - run:
                  command: |
                      cd docker/emptydrops/npz2rds/test/
                      ./test.sh

    test_bulk_rna:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh bulk_rna_pipeline
                  no_output_timeout: 1.5h

    test_sc_atac:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh scATAC
                  no_output_timeout: 1.5h

    test_atac:
        machine:
            image: ubuntu-2004:202201-02
        steps:
            - checkout
            - run:
                  command: |
                      ./tests/skylab/trigger_test.sh ATAC
                  no_output_timeout: 3.0h

    test_smartseq2_single_nucleus:
      machine:
            image: ubuntu-2004:202201-02
      steps:
        - checkout
        - run:
            command: |
              ./tests/skylab/trigger_test.sh smartseq2_single_nucleus
            no_output_timeout: 3.0h

workflows:
    version: 2
    test_all:
        jobs:
            # - test_optimus
            # - test_optimus_snrna
            # #         - test_emptyDropsWrapper
            # - test_optimus_mouse
            # - test_smartseq2
            # - test_smartseq2_single_end
            # - test_smartseq2_single_nucleus
            # #         - test_npz2rds
            # - test_sc_atac
            # - test_atac
            # #         - test_bulk_rna
            # - test_optimus_v3
            # - test_smartseq2_multisample
            # - test_smartseq2_multisample_single_end
