name: dsp-appsec-trivy
on: [pull_request]

jobs:
  build-and-scan:
    # Parse Dockerfile and build, scan image if a "blessed" base image is not used
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        context:
        - dockers/broad/arrays_picard_private
        - dockers/broad/genomes_on_the_cloud
        - dockers/broad/illumina_iaap_autocall
        - dockers/broad/multi_sample
        - dockers/broad/VerifyBamId
        - dockers/broad/zcall
    steps:
      - uses: actions/checkout@v2

      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          context: ${{ matrix.context }}

  prebuilt-scan:
    # scan pre-built images
    name: DSP AppSec Trivy check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
        # TODO please keep these images and tags updated with WDL
        - us.gcr.io/broad-gotc-prod/dsde-toolbox:dev
        - us.gcr.io/broad-gotc-prod/picard-cloud:2.23.8
    steps:
      - uses: broadinstitute/dsp-appsec-trivy-action@v1
        with:
          image: ${{ matrix.image }}
